//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18052.
// 
#pragma warning disable 1591

namespace ADS.LAPEM.Services.wsSIADportal1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="portalSoap", Namespace="http://192.168.3.86:8002/wsSIAD/")]
    public partial class portal : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthHeader authHeaderValueField;
        
        private System.Threading.SendOrPostCallback ConsultaAvisosOperationCompleted;
        
        private System.Threading.SendOrPostCallback getEnviosOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCveLapemOperationCompleted;
        
        private System.Threading.SendOrPostCallback getComercializadoresOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFamiliasOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUnidadesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDsAvisosOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDsPenalizacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDsSeriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardaSolicitudAPOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardaUnAPOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardaSolicitudAPTransformadorOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardaUnAPTransformadorOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public portal() {
            this.Url = global::ADS.LAPEM.Services.Properties.Settings.Default.ADS_LAPEM_Services_wsSIADportal1_portal;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthHeader AuthHeaderValue {
            get {
                return this.authHeaderValueField;
            }
            set {
                this.authHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultaAvisosCompletedEventHandler ConsultaAvisosCompleted;
        
        /// <remarks/>
        public event getEnviosCompletedEventHandler getEnviosCompleted;
        
        /// <remarks/>
        public event getCveLapemCompletedEventHandler getCveLapemCompleted;
        
        /// <remarks/>
        public event getComercializadoresCompletedEventHandler getComercializadoresCompleted;
        
        /// <remarks/>
        public event getFamiliasCompletedEventHandler getFamiliasCompleted;
        
        /// <remarks/>
        public event getUnidadesCompletedEventHandler getUnidadesCompleted;
        
        /// <remarks/>
        public event getDsAvisosCompletedEventHandler getDsAvisosCompleted;
        
        /// <remarks/>
        public event getDsPenalizacionCompletedEventHandler getDsPenalizacionCompleted;
        
        /// <remarks/>
        public event getDsSeriesCompletedEventHandler getDsSeriesCompleted;
        
        /// <remarks/>
        public event GuardaSolicitudAPCompletedEventHandler GuardaSolicitudAPCompleted;
        
        /// <remarks/>
        public event GuardaUnAPCompletedEventHandler GuardaUnAPCompleted;
        
        /// <remarks/>
        public event GuardaSolicitudAPTransformadorCompletedEventHandler GuardaSolicitudAPTransformadorCompleted;
        
        /// <remarks/>
        public event GuardaUnAPTransformadorCompletedEventHandler GuardaUnAPTransformadorCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.3.86:8002/wsSIAD/ConsultaAvisos", RequestNamespace="http://192.168.3.86:8002/wsSIAD/", ResponseNamespace="http://192.168.3.86:8002/wsSIAD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ConsultaAvisos(string Envio) {
            object[] results = this.Invoke("ConsultaAvisos", new object[] {
                        Envio});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaAvisosAsync(string Envio) {
            this.ConsultaAvisosAsync(Envio, null);
        }
        
        /// <remarks/>
        public void ConsultaAvisosAsync(string Envio, object userState) {
            if ((this.ConsultaAvisosOperationCompleted == null)) {
                this.ConsultaAvisosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaAvisosOperationCompleted);
            }
            this.InvokeAsync("ConsultaAvisos", new object[] {
                        Envio}, this.ConsultaAvisosOperationCompleted, userState);
        }
        
        private void OnConsultaAvisosOperationCompleted(object arg) {
            if ((this.ConsultaAvisosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaAvisosCompleted(this, new ConsultaAvisosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.3.86:8002/wsSIAD/getEnvios", RequestNamespace="http://192.168.3.86:8002/wsSIAD/", ResponseNamespace="http://192.168.3.86:8002/wsSIAD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getEnvios() {
            object[] results = this.Invoke("getEnvios", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getEnviosAsync() {
            this.getEnviosAsync(null);
        }
        
        /// <remarks/>
        public void getEnviosAsync(object userState) {
            if ((this.getEnviosOperationCompleted == null)) {
                this.getEnviosOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEnviosOperationCompleted);
            }
            this.InvokeAsync("getEnvios", new object[0], this.getEnviosOperationCompleted, userState);
        }
        
        private void OngetEnviosOperationCompleted(object arg) {
            if ((this.getEnviosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getEnviosCompleted(this, new getEnviosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.3.86:8002/wsSIAD/getCveLapem", RequestNamespace="http://192.168.3.86:8002/wsSIAD/", ResponseNamespace="http://192.168.3.86:8002/wsSIAD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getCveLapem() {
            object[] results = this.Invoke("getCveLapem", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCveLapemAsync() {
            this.getCveLapemAsync(null);
        }
        
        /// <remarks/>
        public void getCveLapemAsync(object userState) {
            if ((this.getCveLapemOperationCompleted == null)) {
                this.getCveLapemOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCveLapemOperationCompleted);
            }
            this.InvokeAsync("getCveLapem", new object[0], this.getCveLapemOperationCompleted, userState);
        }
        
        private void OngetCveLapemOperationCompleted(object arg) {
            if ((this.getCveLapemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCveLapemCompleted(this, new getCveLapemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.3.86:8002/wsSIAD/getComercializadores", RequestNamespace="http://192.168.3.86:8002/wsSIAD/", ResponseNamespace="http://192.168.3.86:8002/wsSIAD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getComercializadores() {
            object[] results = this.Invoke("getComercializadores", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getComercializadoresAsync() {
            this.getComercializadoresAsync(null);
        }
        
        /// <remarks/>
        public void getComercializadoresAsync(object userState) {
            if ((this.getComercializadoresOperationCompleted == null)) {
                this.getComercializadoresOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetComercializadoresOperationCompleted);
            }
            this.InvokeAsync("getComercializadores", new object[0], this.getComercializadoresOperationCompleted, userState);
        }
        
        private void OngetComercializadoresOperationCompleted(object arg) {
            if ((this.getComercializadoresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getComercializadoresCompleted(this, new getComercializadoresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.3.86:8002/wsSIAD/getFamilias", RequestNamespace="http://192.168.3.86:8002/wsSIAD/", ResponseNamespace="http://192.168.3.86:8002/wsSIAD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getFamilias() {
            object[] results = this.Invoke("getFamilias", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getFamiliasAsync() {
            this.getFamiliasAsync(null);
        }
        
        /// <remarks/>
        public void getFamiliasAsync(object userState) {
            if ((this.getFamiliasOperationCompleted == null)) {
                this.getFamiliasOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFamiliasOperationCompleted);
            }
            this.InvokeAsync("getFamilias", new object[0], this.getFamiliasOperationCompleted, userState);
        }
        
        private void OngetFamiliasOperationCompleted(object arg) {
            if ((this.getFamiliasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFamiliasCompleted(this, new getFamiliasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.3.86:8002/wsSIAD/getUnidades", RequestNamespace="http://192.168.3.86:8002/wsSIAD/", ResponseNamespace="http://192.168.3.86:8002/wsSIAD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getUnidades() {
            object[] results = this.Invoke("getUnidades", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getUnidadesAsync() {
            this.getUnidadesAsync(null);
        }
        
        /// <remarks/>
        public void getUnidadesAsync(object userState) {
            if ((this.getUnidadesOperationCompleted == null)) {
                this.getUnidadesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUnidadesOperationCompleted);
            }
            this.InvokeAsync("getUnidades", new object[0], this.getUnidadesOperationCompleted, userState);
        }
        
        private void OngetUnidadesOperationCompleted(object arg) {
            if ((this.getUnidadesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUnidadesCompleted(this, new getUnidadesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.3.86:8002/wsSIAD/getDsAvisos", RequestNamespace="http://192.168.3.86:8002/wsSIAD/", ResponseNamespace="http://192.168.3.86:8002/wsSIAD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getDsAvisos() {
            object[] results = this.Invoke("getDsAvisos", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getDsAvisosAsync() {
            this.getDsAvisosAsync(null);
        }
        
        /// <remarks/>
        public void getDsAvisosAsync(object userState) {
            if ((this.getDsAvisosOperationCompleted == null)) {
                this.getDsAvisosOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDsAvisosOperationCompleted);
            }
            this.InvokeAsync("getDsAvisos", new object[0], this.getDsAvisosOperationCompleted, userState);
        }
        
        private void OngetDsAvisosOperationCompleted(object arg) {
            if ((this.getDsAvisosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDsAvisosCompleted(this, new getDsAvisosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.3.86:8002/wsSIAD/getDsPenalizacion", RequestNamespace="http://192.168.3.86:8002/wsSIAD/", ResponseNamespace="http://192.168.3.86:8002/wsSIAD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getDsPenalizacion() {
            object[] results = this.Invoke("getDsPenalizacion", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getDsPenalizacionAsync() {
            this.getDsPenalizacionAsync(null);
        }
        
        /// <remarks/>
        public void getDsPenalizacionAsync(object userState) {
            if ((this.getDsPenalizacionOperationCompleted == null)) {
                this.getDsPenalizacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDsPenalizacionOperationCompleted);
            }
            this.InvokeAsync("getDsPenalizacion", new object[0], this.getDsPenalizacionOperationCompleted, userState);
        }
        
        private void OngetDsPenalizacionOperationCompleted(object arg) {
            if ((this.getDsPenalizacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDsPenalizacionCompleted(this, new getDsPenalizacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.3.86:8002/wsSIAD/getDsSeries", RequestNamespace="http://192.168.3.86:8002/wsSIAD/", ResponseNamespace="http://192.168.3.86:8002/wsSIAD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getDsSeries() {
            object[] results = this.Invoke("getDsSeries", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getDsSeriesAsync() {
            this.getDsSeriesAsync(null);
        }
        
        /// <remarks/>
        public void getDsSeriesAsync(object userState) {
            if ((this.getDsSeriesOperationCompleted == null)) {
                this.getDsSeriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDsSeriesOperationCompleted);
            }
            this.InvokeAsync("getDsSeries", new object[0], this.getDsSeriesOperationCompleted, userState);
        }
        
        private void OngetDsSeriesOperationCompleted(object arg) {
            if ((this.getDsSeriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDsSeriesCompleted(this, new getDsSeriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.3.86:8002/wsSIAD/GuardaSolicitudAP", RequestNamespace="http://192.168.3.86:8002/wsSIAD/", ResponseNamespace="http://192.168.3.86:8002/wsSIAD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GuardaSolicitudAP(System.Data.DataSet Sol_Avisos, System.Data.DataSet SolSeries, string _SolicitaAP) {
            object[] results = this.Invoke("GuardaSolicitudAP", new object[] {
                        Sol_Avisos,
                        SolSeries,
                        _SolicitaAP});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GuardaSolicitudAPAsync(System.Data.DataSet Sol_Avisos, System.Data.DataSet SolSeries, string _SolicitaAP) {
            this.GuardaSolicitudAPAsync(Sol_Avisos, SolSeries, _SolicitaAP, null);
        }
        
        /// <remarks/>
        public void GuardaSolicitudAPAsync(System.Data.DataSet Sol_Avisos, System.Data.DataSet SolSeries, string _SolicitaAP, object userState) {
            if ((this.GuardaSolicitudAPOperationCompleted == null)) {
                this.GuardaSolicitudAPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardaSolicitudAPOperationCompleted);
            }
            this.InvokeAsync("GuardaSolicitudAP", new object[] {
                        Sol_Avisos,
                        SolSeries,
                        _SolicitaAP}, this.GuardaSolicitudAPOperationCompleted, userState);
        }
        
        private void OnGuardaSolicitudAPOperationCompleted(object arg) {
            if ((this.GuardaSolicitudAPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardaSolicitudAPCompleted(this, new GuardaSolicitudAPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.3.86:8002/wsSIAD/GuardaUnAP", RequestNamespace="http://192.168.3.86:8002/wsSIAD/", ResponseNamespace="http://192.168.3.86:8002/wsSIAD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GuardaUnAP(System.Data.DataSet Sol_Avisos, System.Data.DataSet SolSeries, string _SolicitaAP) {
            object[] results = this.Invoke("GuardaUnAP", new object[] {
                        Sol_Avisos,
                        SolSeries,
                        _SolicitaAP});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GuardaUnAPAsync(System.Data.DataSet Sol_Avisos, System.Data.DataSet SolSeries, string _SolicitaAP) {
            this.GuardaUnAPAsync(Sol_Avisos, SolSeries, _SolicitaAP, null);
        }
        
        /// <remarks/>
        public void GuardaUnAPAsync(System.Data.DataSet Sol_Avisos, System.Data.DataSet SolSeries, string _SolicitaAP, object userState) {
            if ((this.GuardaUnAPOperationCompleted == null)) {
                this.GuardaUnAPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardaUnAPOperationCompleted);
            }
            this.InvokeAsync("GuardaUnAP", new object[] {
                        Sol_Avisos,
                        SolSeries,
                        _SolicitaAP}, this.GuardaUnAPOperationCompleted, userState);
        }
        
        private void OnGuardaUnAPOperationCompleted(object arg) {
            if ((this.GuardaUnAPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardaUnAPCompleted(this, new GuardaUnAPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.3.86:8002/wsSIAD/GuardaSolicitudAPTransformador", RequestNamespace="http://192.168.3.86:8002/wsSIAD/", ResponseNamespace="http://192.168.3.86:8002/wsSIAD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GuardaSolicitudAPTransformador(System.Data.DataSet Sol_Avisos, System.Data.DataSet SolSeries, string _SolicitaAP, System.Data.DataSet SolPenalizacion) {
            object[] results = this.Invoke("GuardaSolicitudAPTransformador", new object[] {
                        Sol_Avisos,
                        SolSeries,
                        _SolicitaAP,
                        SolPenalizacion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GuardaSolicitudAPTransformadorAsync(System.Data.DataSet Sol_Avisos, System.Data.DataSet SolSeries, string _SolicitaAP, System.Data.DataSet SolPenalizacion) {
            this.GuardaSolicitudAPTransformadorAsync(Sol_Avisos, SolSeries, _SolicitaAP, SolPenalizacion, null);
        }
        
        /// <remarks/>
        public void GuardaSolicitudAPTransformadorAsync(System.Data.DataSet Sol_Avisos, System.Data.DataSet SolSeries, string _SolicitaAP, System.Data.DataSet SolPenalizacion, object userState) {
            if ((this.GuardaSolicitudAPTransformadorOperationCompleted == null)) {
                this.GuardaSolicitudAPTransformadorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardaSolicitudAPTransformadorOperationCompleted);
            }
            this.InvokeAsync("GuardaSolicitudAPTransformador", new object[] {
                        Sol_Avisos,
                        SolSeries,
                        _SolicitaAP,
                        SolPenalizacion}, this.GuardaSolicitudAPTransformadorOperationCompleted, userState);
        }
        
        private void OnGuardaSolicitudAPTransformadorOperationCompleted(object arg) {
            if ((this.GuardaSolicitudAPTransformadorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardaSolicitudAPTransformadorCompleted(this, new GuardaSolicitudAPTransformadorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.3.86:8002/wsSIAD/GuardaUnAPTransformador", RequestNamespace="http://192.168.3.86:8002/wsSIAD/", ResponseNamespace="http://192.168.3.86:8002/wsSIAD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GuardaUnAPTransformador(System.Data.DataSet Sol_Avisos, System.Data.DataSet SolSeries, string _SolicitaAP, System.Data.DataSet SolPenalizacion) {
            object[] results = this.Invoke("GuardaUnAPTransformador", new object[] {
                        Sol_Avisos,
                        SolSeries,
                        _SolicitaAP,
                        SolPenalizacion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GuardaUnAPTransformadorAsync(System.Data.DataSet Sol_Avisos, System.Data.DataSet SolSeries, string _SolicitaAP, System.Data.DataSet SolPenalizacion) {
            this.GuardaUnAPTransformadorAsync(Sol_Avisos, SolSeries, _SolicitaAP, SolPenalizacion, null);
        }
        
        /// <remarks/>
        public void GuardaUnAPTransformadorAsync(System.Data.DataSet Sol_Avisos, System.Data.DataSet SolSeries, string _SolicitaAP, System.Data.DataSet SolPenalizacion, object userState) {
            if ((this.GuardaUnAPTransformadorOperationCompleted == null)) {
                this.GuardaUnAPTransformadorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardaUnAPTransformadorOperationCompleted);
            }
            this.InvokeAsync("GuardaUnAPTransformador", new object[] {
                        Sol_Avisos,
                        SolSeries,
                        _SolicitaAP,
                        SolPenalizacion}, this.GuardaUnAPTransformadorOperationCompleted, userState);
        }
        
        private void OnGuardaUnAPTransformadorOperationCompleted(object arg) {
            if ((this.GuardaUnAPTransformadorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardaUnAPTransformadorCompleted(this, new GuardaUnAPTransformadorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://192.168.3.86:8002/wsSIAD/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://192.168.3.86:8002/wsSIAD/", IsNullable=false)]
    public partial class AuthHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ConsultaAvisosCompletedEventHandler(object sender, ConsultaAvisosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaAvisosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaAvisosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getEnviosCompletedEventHandler(object sender, getEnviosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getEnviosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getEnviosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getCveLapemCompletedEventHandler(object sender, getCveLapemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCveLapemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCveLapemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getComercializadoresCompletedEventHandler(object sender, getComercializadoresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getComercializadoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getComercializadoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getFamiliasCompletedEventHandler(object sender, getFamiliasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFamiliasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFamiliasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getUnidadesCompletedEventHandler(object sender, getUnidadesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUnidadesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUnidadesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getDsAvisosCompletedEventHandler(object sender, getDsAvisosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDsAvisosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDsAvisosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getDsPenalizacionCompletedEventHandler(object sender, getDsPenalizacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDsPenalizacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDsPenalizacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getDsSeriesCompletedEventHandler(object sender, getDsSeriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDsSeriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDsSeriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GuardaSolicitudAPCompletedEventHandler(object sender, GuardaSolicitudAPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardaSolicitudAPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardaSolicitudAPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GuardaUnAPCompletedEventHandler(object sender, GuardaUnAPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardaUnAPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardaUnAPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GuardaSolicitudAPTransformadorCompletedEventHandler(object sender, GuardaSolicitudAPTransformadorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardaSolicitudAPTransformadorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardaSolicitudAPTransformadorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GuardaUnAPTransformadorCompletedEventHandler(object sender, GuardaUnAPTransformadorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardaUnAPTransformadorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardaUnAPTransformadorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591