//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADS.LAPEM.Resources.Catalogo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LAPEM_Entities_Proveedor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LAPEM_Entities_Proveedor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADS.LAPEM.Resources.Catalogo.LAPEM_Entities_Proveedor", typeof(LAPEM_Entities_Proveedor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Ciudad es obligatorio.
        /// </summary>
        public static string Ciudad_Required {
            get {
                return ResourceManager.GetString("Ciudad_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Dirección es obligatorio.
        /// </summary>
        public static string Direccion_Required {
            get {
                return ResourceManager.GetString("Direccion_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Estado es obligatorio.
        /// </summary>
        public static string Estado_Required {
            get {
                return ResourceManager.GetString("Estado_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Nombre es obligatorio.
        /// </summary>
        public static string Nombre_Required {
            get {
                return ResourceManager.GetString("Nombre_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo RFC es obligatorio.
        /// </summary>
        public static string RFC_Required {
            get {
                return ResourceManager.GetString("RFC_Required", resourceCulture);
            }
        }
    }
}
