// <auto-generated />
namespace ADS.LAPEM.Repositories.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AjustesEnNorma : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AjustesEnNorma));
        
        string IMigrationMetadata.Id
        {
            get { return "201311120037534_AjustesEnNorma"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
